stages:
  - build
  - deploy
  - test

image: openmole/build

assemble:
  stage: build
  artifacts:
    paths:
      - ./openmole/site/
      - ./openmole/bin/tests/
  script:
    #- bash -x build.sh
    #- '(cd openmole && sbt test)' # Metaspace error to be solved
    - git lfs fetch
    - '(cd ./build-system && sbt --version)'
    - '(cd ./build-system && sbt publishLocal)'
    - '(cd ./libraries && sbt publishLocal)'
    - '(cd ./openmole && ./generateSite $PWD/site)'
    - '(cd ./openmole && sbt "project tests" assemble)'

publish-next:
  stage: deploy
  environment:
    name: next-site
  dependencies: 
    - assemble
  resource_group: next
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat $SSH_PRIVATE_KEY >~/.ssh/identity
    - chmod 400 ~/.ssh/identity
    - ssh-keyscan -p 9000 docker.openmole.org > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "put -r ./openmole/site/* next" >./tonext     
    - sftp -i ~/.ssh/identity -b ./tonext -P 9000 user@docker.openmole.org

publish-docker:
  stage: deploy
  environment:
    name: docker-dev
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - '(cat $DOCKER_TOKEN | docker login -u "$DOCKER_USER" --password-stdin)'
  resource_group: docker
  script:
    - docker info
    - '(cd ./build-system && sbt --version)'
    - '(cd ./build-system && sbt publishLocal)'
    - '(cd ./libraries && sbt publishLocal)'
    - '(cd ./openmole && sbt "project docker" dockerBuildAndPush && docker push openmole/openmole:latest)'
  
test-site:
  stage: test
  needs: ["assemble"]
  dependencies: 
    - assemble
  script:
    - (mkdir extracted && (cd extracted && tar -xvzf ../openmole/site/openmole.tar.gz && export OPENMOLE=$PWD/openmole/openmole) && $OPENMOLE --test-compile openmole/bin/tests/assemble)

    