stages:
  - build
  - test

image: openmole/build

assemble:
  stage: build
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
  environment:
    name: deploy
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - '(cat $DOCKER_TOKEN | docker login -u "$DOCKER_USER" --password-stdin)'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat $SSH_PRIVATE_KEY >~/.ssh/identity
    - chmod 400 ~/.ssh/identity
    - ssh-keyscan -p 9000 docker.openmole.org > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  #artifacts:
  #  paths:
  #    - ./openmole/site/
  #    - ./openmole/bin/tests/target/assemble/tests/
  #    - ./openmole/bin/docker/target/docker
  script:
    #- bash -x build.sh
    #- '(cd openmole && sbt test)' # Metaspace error to be solved
    - git lfs fetch
    - '(cd ./build-system && sbt --version)'
    - '(cd ./build-system && sbt publishLocal)'
    - '(cd ./libraries && sbt publishLocal)'
    - '(cd ./openmole && ./generateSite $PWD/site)'
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - echo "put -r ./openmole/site/* next" >./tonext     
    - sftp -i ~/.ssh/identity -b ./tonext -P 9000 user@docker.openmole.org
    - '(cd ./openmole && sbt "project docker" dockerBuildAndPush "project tests" assemble)'  
    - '(cd ./openmole && ./bin/openmole/target/assemble/openmole --test-compile ./bin/tests/target/assemble/tests/)'

unit-tests:
  stage: test
  script:
    - '(cd ./build-system && sbt --version)'
    - '(cd ./build-system && sbt publishLocal)'
    - '(cd ./libraries && sbt publishLocal)'
    - '(cd ./openmole && sbt -J-Xmx4G test)'

