stages:
  - build
  - publish

image: openmole/build

assemble:
  stage: build
  artifacts:
    paths:
      - ./openmole/site/
  script:
    #- bash -x build.sh
    #- '(cd openmole && sbt test)' # Metaspace error to be solved
    - git lfs fetch
    - '(cd ./build-system && sbt --version)'
    - '(cd ./build-system && sbt publishLocal)'
    - '(cd ./libraries && sbt publishLocal)'
    - '(cd ./openmole && ./generateSite $PWD/site)'

publish-next:
  stage: publish
  dependencies: 
    - assemble
  resource_group: next
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    #refs:
    #  - 11-dev
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat $SSH_PRIVATE_KEY >~/.ssh/identity
    - chmod 400 ~/.ssh/identity
    - ssh-keyscan -p 9000 docker.openmole.org > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "put -r ./openmole/site/* next" >./tonext     
    - sftp -i ~/.ssh/identity -b ./tonext -P 9000 user@docker.openmole.org
    
publish-docker:
  stage: publish
  image: docker:latest
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_TOKEN" 
  services:
    - docker:dind
  resource_group: docker
  script:
    - docker info
    - '(cd ./build-system && sbt --version)'
    - '(cd ./build-system && sbt publishLocal)'
    - '(cd ./libraries && sbt publishLocal)'
    - '(cd ./openmole && sbt "project docker" docker)'
    - (cd ./openmole && version=$(cat version.sbt | grep version | cut -d' ' -f 5 | sed 's\"\\g') && docker push openmole/openmole:$version && docker rmi -f openmole/openmole:$version)
    