stages:
  - build
  - publish

image: openmole/build

publish-docker:
  stage: publish
  image: openmole/build
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - '(cat $DOCKER_TOKEN | docker login -u "$DOCKER_USER" --password-stdin)'
  services:
    - docker:dind
  resource_group: docker
  script:
    - docker info
    - '(cd ./build-system && sbt --version)'
    - '(cd ./build-system && sbt publishLocal)'
    - '(cd ./libraries && sbt publishLocal)'
    - '(cd ./openmole && sbt "project docker" docker)'
    - (cd ./openmole && version=$(cat version.sbt | grep version | cut -d' ' -f 5 | sed 's\"\\g') && docker push openmole/openmole:$version && docker rmi -f openmole/openmole:$version)
    